Fix password confirmed, readme, .env.exemple
AezardSR/Le_Flamant_Bleu_API pull request #25
Opened 2023-03-21 15:47 UTC by AezardSR

close https://github.com/AezardSR/Le_Flamant_Bleu_API/issues/15
close https://github.com/AezardSR/Le_Flamant_Bleu_API/issues/16
close https://github.com/AezardSR/Le_Flamant_Bleu_API/issues/18

2023-03-22 09:58 UTC, MercierCorentin approved these changes

2023-03-22 10:08 UTC, MercierCorentin requested changes

2023-03-22 10:08 UTC, MercierCorentin commented on .env.example
> -DB_HOST=db
Comme c'est pas une conf évidente si on maitrise pas bien docker, il vaut mieux laisser le nom du conteneur dans host

2023-03-22 10:08 UTC, MercierCorentin commented on .env.example
> -DB_PASSWORD=laravel
Idem ici, tu peux laisser les mots de passe par défaut de dev

2023-03-22 10:08 UTC, MercierCorentin commented on .env.example
> +L5_SWAGGER_CONST_HOST= l'URL de base pour l'API de votre application Laravel pour la documentation Swagger
Proposer une valeur par défaut qui fonctionne permet de simplifier la première mise en place locale

2023-03-22 11:06 UTC, AezardSR commented on .env.example
> +L5_SWAGGER_CONST_HOST= l'URL de base pour l'API de votre application Laravel pour la documentation Swagger
c'est mieux ?

2023-03-22 11:15 UTC, AezardSR commented on .env.example
> -DB_PASSWORD=laravel
c'est corrigé

2023-03-22 11:16 UTC, AezardSR commented on .env.example
> -DB_HOST=db
c'est corrigé

2023-03-24 10:30 UTC, MercierCorentin approved these changes

2023-03-24 10:31 UTC, merged